export const META = {
  course: "DSEH001",
  title: "Digital Transformation in Human Resource Systems",
  programme: "M.Com. PGCF 2025",
  institution: "Faculty of Commerce and Business · Delhi School of Economics · University of Delhi",
  instructor: "Prof. R.K. Singh",
  cohort: "Cohort 1 · AY 2026–27",
  simulationURL: "https://disha-simultaion.vercel.app",
};

export const CLO_MAP = [
  { id: "CLO1", label: "Drivers & Maturity", bloom: "Understand / Analyse", color: "#6C63D4" },
  { id: "CLO2", label: "Platforms & Tools", bloom: "Apply / Analyse", color: "#15A06B" },
  { id: "CLO3", label: "Evaluate Analytics & AI", bloom: "Evaluate", color: "#C2376A" },
  { id: "CLO4", label: "Design Interventions", bloom: "Create", color: "#C07A10" },
  { id: "CLO5", label: "Ethics, Fairness & Change", bloom: "Evaluate", color: "#2277CC" },
];

export const ASSESSMENTS = [
  { label: "Quiz 1", week: 2, text: "Drivers, Industry 4.0, maturity models", round: "R1", color: "#6C63D4" },
  { label: "Quiz 2", week: 4, text: "Data literacy, BI, ethics", round: "R2", color: "#15A06B" },
  { label: "Quiz 3", week: 6, text: "HRIS, ATS, LMS, adoption, mobile HR", round: "R3", color: "#E05830" },
  { label: "Quiz 4", week: 9, text: "Analytics, algorithmic HR, fairness", round: "R4", color: "#C2376A" },
  { label: "Quiz 5", week: 11, text: "Future of work, gig economy, change agent", round: "R6", color: "#2277CC" },
  { label: "D1", week: 6, text: "Maturity & Tech-Stack Blueprint (R1-R3)", round: "R2/R3", color: "#E05830", deliverable: true },
  { label: "D2", week: 11, text: "Future-of-Work Board Memo (R4-R6)", round: "R5/R6", color: "#2277CC", deliverable: true },
];

export const ANCHORS = [
  {
    id: "GL-1001", name: "Lakshmi Naidu", color: "#6C63D4",
    profile: "Tier-3 frontline · Smartphone-only · Digital Literacy 2",
    rounds: ["R1","R2","R3","R6"],
    question: "Does your decision reach a worker with no laptop, intermittent connectivity, and basic digital literacy?",
  },
  {
    id: "GL-1002", name: "Arjun Joshi", color: "#E05830",
    profile: "Bronze gig · Chennai · Rs 11,400/month · Not enrolled · 5 grievances",
    rounds: ["R2","R5","R6"],
    question: "Does the strategy address his cohort with Gig_Workforce data? The R5 allegations are accurate -- verify before writing.",
  },
  {
    id: "GL-1003", name: "Sunil Mehta", color: "#15A06B",
    profile: "HR Officer · Lucknow · Tier-1 · 204 months tenure · Literacy 3",
    rounds: ["R1","R3"],
    question: "Is there a structured transition path for a long-tenure mid-career employee, beyond a training module?",
  },
  {
    id: "GL-1004", name: "Shreya Iyer", color: "#C2376A",
    profile: "HQ Analyst · Top-quartile engagement · Model flags HIGH risk",
    rounds: ["R1","R4"],
    question: "What does the model say about her? What is the consequence for employees like her if no remediation occurs?",
  },
];

export const ROUNDS = [
  {
    id: "R1", code: "R1",
    title: "The Diagnosis",
    subtitle: "Digital HR Maturity & Workforce Readiness",
    unit: "Unit I", weeks: "Weeks 2-3",
    color: "#6C63D4", colorLight: "#EEF0FF", colorDark: "#3D3699", colorMid: "#9B94E8",
    dataset: ["Digital_HR_Maturity","Employee_Master"],
    planted: "Digital divide: literacy ~2.4 frontline vs ~4.0 non-frontline; smartphone-only skew by tier",
    clos: ["CLO1","CLO4","CLO5"],
    theories: [
      "Westerman et al. (2014) -- Digital masters transformation grid",
      "Schwab (2016) -- Industry 4.0 drivers",
      "Kavanagh -- HR Tech Maturity Stage 1",
      "Digital Divide Framework: Access to Skills to Use",
      "Bersin -- HR Analytics maturity tiers",
      "Kotter -- Step 1: Create urgency from evidence",
    ],
    anchorsActive: ["GL-1001","GL-1003","GL-1004"],
    assessments: ["Quiz 1"],
    options: [
      {
        code: "1A", name: "Foundations First",
        tagline: "Commission a device & connectivity audit before any platform decisions",
        cost: { budget: 40, hours: 8, cc: 0 },
        theory: "Kavanagh HR Tech Maturity Model Stage 1: diagnose before prescribing. Westerman's digital-maturity grid: technology capability must match leadership readiness before investment. Kotter Step 1: urgency requires a gap made visible through hard evidence. Most conservative budget, ideal when the team suspects infrastructure blind spots.",
        clos: ["CLO1","CLO4"],
        lectureLink: "W2 L2 -- maturity models · W3 L1 -- data literacy",
        pedagogy: "Teaches evidence-gathering discipline; the right choice when data quality is uncertain.",
        grade: "strong",
      },
      {
        code: "1B", name: "Analytics-First Leap",
        tagline: "Deploy a people-analytics platform immediately",
        cost: { budget: 80, hours: 18, cc: -5 },
        theory: "Bersin HR Analytics maturity: jumping tiers without data quality creates compounding errors in R4-R5. Marler & Boudreau (2017): HR analytics fails when built on bad data. Angrave et al. (2016): the big-data challenge in HR -- analytics infrastructure is not the bottleneck, data quality is. The Change Capital penalty signals internal resistance when analytics precedes trust.",
        clos: ["CLO1","CLO3"],
        lectureLink: "W2 L2 -- digital maturity stage vs leap · W7 -- analytics cascade risk",
        pedagogy: "Pedagogical trap: teaches why impressive does not equal grounded. The R4 confusion matrix will be worse for teams that chose 1B without first fixing data quality.",
        grade: "risk",
      },
      {
        code: "1C", name: "Mobile-First Equity Lens",
        tagline: "Survey mobile access & digital literacy by Location Tier",
        cost: { budget: 60, hours: 12, cc: 5 },
        theory: "Digital Divide Framework: three layers -- Access, Skills, Use. Scully-Russ (2019): the people dimension of transformation is the binding constraint. Manuti & de Palma (2023): critical lens on who technology excludes. India Stack and vernacular access for Tier-3. GL-1001 Lakshmi Naidu as the test case. Best foundation for R3 adoption design.",
        clos: ["CLO1","CLO4","CLO5"],
        lectureLink: "W3 L2 -- digital divide · W5 -- frontline-first design · W6 -- GL-1001 anchor",
        pedagogy: "Best option for teams who want to build toward Equity & Compliance axis strength across all six rounds.",
        grade: "strong",
      },
      {
        code: "1D", name: "Regulatory Alignment Thesis",
        tagline: "Begin with DPDP Act 2023 & SS2020 compliance gap analysis",
        cost: { budget: 50, hours: 10, cc: 3 },
        theory: "DPDP Act 2023: consent, purpose-limitation, data-minimisation from the start (Privacy by Design). Code on Social Security 2020 for gig coverage. Stone et al. (2015): legal-regulatory environment as transformation driver. Earns Change Capital through governance credibility. Teams choosing 1D have significantly lower Shock 1 damage in R3 because DPDP governance was front-loaded.",
        clos: ["CLO1","CLO5"],
        lectureLink: "W3 L2 -- ethics & DPDP Act · W6 -- DPDP feeds directly into R3 shock response",
        pedagogy: "The regulatory first thesis: teaches that governance is not a bolt-on. Cascades cleanly through R2D to R3 with lower Shock 1 penalty.",
        grade: "strong",
      },
    ],
  },
  {
    id: "R2", code: "R2",
    title: "The Architecture",
    subtitle: "HR Tech Stack, HRIS Integration & India Stack",
    unit: "Unit II", weeks: "Weeks 4-5",
    color: "#15A06B", colorLight: "#E0F7EE", colorDark: "#0A6644", colorMid: "#52C99A",
    dataset: ["TechStack_Inventory","Employee_Master"],
    planted: "Dual-HRIS migration conflict; low-adoption point solutions; shadow spreadsheets",
    clos: ["CLO2","CLO4","CLO5"],
    deliverable: "D1 -- Maturity & Tech-Stack Blueprint (due close of R2)",
    theories: [
      "Kavanagh -- System of Record + Engagement + Insight (three-layer architecture)",
      "Bondarouk, Parry & Furtmueller (2017) -- e-HRM adoption consequences",
      "Privacy by Design -- ISO 27701 / DPDP Act 2023",
      "Bersin -- Modular vs suite HR tech ecosystem design",
      "India Stack -- UPI, DigiLocker, Aadhaar-eKYC integration",
      "Davenport, Harris & Shapiro (2010) -- Competing on talent analytics",
    ],
    anchorsActive: ["GL-1001","GL-1002"],
    assessments: ["Quiz 2","D1"],
    options: [
      {
        code: "2A", name: "Modular HRMS Core",
        tagline: "Retire on-premise redundancies; consolidate on cloud HRIS",
        cost: { budget: 120, hours: 20, cc: -5 },
        theory: "Kavanagh HRIS implementation lifecycle Stage 2-3: System of Record consolidation creates a single source of truth, resolving GreenLeaf's triple-spreadsheet problem. Bondarouk et al.: adoption depends on perceived usefulness and system stability -- a stable core reduces resistance. Suite vs best-of-breed: this is the stable foundation first answer before adding analytics modules.",
        clos: ["CLO2","CLO4"],
        lectureLink: "W4 L1 -- HRIS system of record · W4 L3 -- stack-design architecture",
        pedagogy: "Solid, defensible, coherent with 1A or 1C. Leaves adequate budget for R4 retraining. Teaches phased architecture discipline.",
        grade: "strong",
      },
      {
        code: "2B", name: "People Analytics Platform",
        tagline: "Deploy standalone analytics on existing payroll -- fast insights, integration debt",
        cost: { budget: 150, hours: 25, cc: -8 },
        theory: "Bersin analytics maturity: fast insights but integration debt compounds. Davenport, Harris & Shapiro (2010): talent analytics requires clean pipelines -- analytics on GreenLeaf's legacy data creates compounding interpretation errors in R4 and R5. Angrave et al. (2016): HR analytics fails the big-data challenge when data quality is not addressed first. Most expensive R2 option after 2C.",
        clos: ["CLO2","CLO3"],
        lectureLink: "W4 -- HRIS · W7 -- analytics ladder (downstream risk if data quality skipped)",
        pedagogy: "Highest-risk choice: if R1 skipped the baseline, analytics on poor data will create cascading errors through the signature R4 round.",
        grade: "risk",
      },
      {
        code: "2C", name: "Integrated Talent Suite",
        tagline: "Full suite: HRMS + analytics + learning in one deployment",
        cost: { budget: 180, hours: 30, cc: -10 },
        theory: "HR technology ecosystem design: the big bang implementation. Bondarouk et al.: big-bang rollouts correlate strongly with high resistance and failed adoption. Kavanagh Stage 3+ requires organisational readiness GreenLeaf does not yet have. Critical Financial Discipline trap -- spending Rs 180L in R2 leaves only Rs 420L for the remaining four rounds, constraining retraining options in R4.",
        clos: ["CLO2","CLO4"],
        lectureLink: "W4 L1 -- suite vs best-of-breed · W6 -- integration debt · W8 -- dashboard design",
        pedagogy: "Deliberately costly: forces teams to confront the budget math early. The debrief question is: What does this leave for R4 retraining?",
        grade: "risk",
      },
      {
        code: "2D", name: "Mobile-First Lightweight",
        tagline: "Mobile-first HRMS optimised for frontline and Tier-2/3 employees",
        cost: { budget: 90, hours: 15, cc: 5 },
        theory: "Digital inclusion framework: GL-1001's smartphone-only reality is the binding constraint. India Stack: DigiLocker and Aadhaar-eKYC enable frontline digital onboarding without a desktop. Bondarouk et al.: mobile-first design increases perceived usefulness among frontline populations. Earns +5 Change Capital by demonstrating frontline-centricity. Lowest DPDP risk when data stays minimal and local.",
        clos: ["CLO2","CLO4","CLO5"],
        lectureLink: "W5 -- digital onboarding, India Stack · W6 L1 -- mobile HR · W5 L3 -- GL-1001 anchor",
        pedagogy: "Best Equity & Compliance axis choice at R2. Coherent with 1C (Mobile-First Equity Lens). The digital inclusion thesis begins to pay off.",
        grade: "strong",
      },
    ],
  },
  {
    id: "R3", code: "R3",
    title: "The Rollout",
    subtitle: "Change Management, Adoption & Digital Learning",
    unit: "Unit II-III", weeks: "Week 6",
    color: "#E05830", colorLight: "#FFF0EB", colorDark: "#8C3218", colorMid: "#F0855E",
    dataset: ["Adoption_Telemetry","LMS_Learning"],
    planted: "Frontline adoption gap; training-completion failures among smartphone-only staff",
    shock: {
      title: "Shock 1 -- DPDP Data Breach",
      text: "340 frontline workers' Aadhaar-linked payroll data exposed via misconfigured cloud bucket. 72-hour DPDP notification required. Fires automatically on Submit -- no instructor action needed.",
      color: "#E05830",
    },
    clos: ["CLO2","CLO4","CLO5"],
    theories: [
      "Prosci ADKAR -- Awareness to Desire to Knowledge to Ability to Reinforcement",
      "Kotter 8-Step -- Steps 3-5: create vision, communicate, empower broad-based action",
      "Rogers -- Diffusion of Innovation (change agents as accelerators)",
      "UTAUT -- adoption predictors: performance expectancy, effort expectancy, social influence",
      "Digital Inclusion -- bandwidth and literacy as structural constraints",
      "DPDP Act 2023 -- 72-hour breach notification obligation",
    ],
    anchorsActive: ["GL-1001","GL-1003"],
    assessments: ["Quiz 3","D1"],
    options: [
      {
        code: "3A", name: "Phased Rollout -- Pilot First",
        tagline: "Pilot in one Location Tier before committing to full rollout",
        cost: { budget: 60, hours: 12, cc: 5 },
        theory: "Lewin's change model: unfreeze in a controlled pilot, generate learning, then refreeze at scale. ADKAR stage analysis: moves frontline from Awareness to Trial safely, gathering real adoption telemetry before budget commitment. UTAUT: pilot reduces perceived risk for resistant users. The test and learn thesis -- highest on Financial Discipline axis.",
        clos: ["CLO2","CLO4"],
        lectureLink: "W6 L2 -- UTAUT adoption predictors · W6 -- when to scale vs pause",
        pedagogy: "Teaches data-driven course-correction. Pairs well with 1A or 1C R1 choices. Change Capital gain reflects the goodwill earned by not forcing a big-bang rollout.",
        grade: "strong",
      },
      {
        code: "3B", name: "Full Rollout + Intensive Training",
        tagline: "Deploy across all locations simultaneously with mandatory training",
        cost: { budget: 100, hours: 20, cc: -5 },
        theory: "Kotter's 8-step -- the big push version of Step 5 (empower broad-based action). Critical limitation: training does not solve an access problem; communication does not solve a skill problem. Classroom or desktop-only training structurally excludes GL-1001 by design. Bondarouk et al.: top-down mandate rollouts face higher resistance in frontline populations. High budget, highest Change Capital burn.",
        clos: ["CLO2","CLO4"],
        lectureLink: "W6 L1 -- Kotter 8-step · W5 -- LMS completion gaps by literacy tier",
        pedagogy: "The contrast choice: expensive, pedagogically revealing. Debrief question -- Can GL-1001 complete onboarding training on her feature phone through this method?",
        grade: "risk",
      },
      {
        code: "3C", name: "Change Agent Network",
        tagline: "Train internal champions in each Location Tier",
        cost: { budget: 50, hours: 10, cc: 10 },
        theory: "Rogers' Diffusion of Innovation: early adopters as change agents accelerate the S-curve across peer segments far more efficiently than top-down mandates. ADKAR: peer influence addresses the Desire stage where top-down training fails. Kotter Step 5: empower broad-based action via distributed champions. GL-1003 Sunil Mehta is the ideal champion archetype -- long-tenure, mid-career, trusted by peers. Highest Change Capital gain of any R3 option.",
        clos: ["CLO2","CLO4","CLO5"],
        lectureLink: "W6 L2 -- Rogers adoption curve · W5 -- GL-1003 transition path · W6 L3 -- D1 integration",
        pedagogy: "The pedagogically richest R3 choice: teaches peer learning, bottom-up change, and the distinction between change management and communication campaigns.",
        grade: "strong",
      },
      {
        code: "3D", name: "Gamified Adoption Campaign",
        tagline: "Leaderboards and incentives for digital engagement",
        cost: { budget: 70, hours: 14, cc: 8 },
        theory: "Behavioural nudge design and gamification (Thaler & Sunstein applied to HR tech adoption). UTAUT: performance expectancy driven by visible rewards. Critical risk: superficial adoption -- high login counts but low meaningful self-service transactions. Manuti & de Palma (2023): digital HR tools can surveil under the guise of engagement. Raises digital equity questions when Tier-3 employees with feature phones cannot participate equally in leaderboard mechanics.",
        clos: ["CLO2","CLO4","CLO5"],
        lectureLink: "W6 L1 -- engagement apps · W8 L2 -- metric gaming vs genuine adoption",
        pedagogy: "Teaches the critical distinction between metric gaming and genuine behavioural change. The Ethics & Worker Voice role should challenge whether leaderboard mechanics are equitable across device types.",
        grade: "caution",
      },
    ],
  },
  {
    id: "R4", code: "R4",
    title: "The Audit",
    subtitle: "People Analytics, Algorithmic Fairness & AI Governance",
    unit: "Unit III", weeks: "Weeks 7-8",
    color: "#C2376A", colorLight: "#FDEDF3", colorDark: "#7A1D40", colorMid: "#E06B96",
    dataset: ["Recruitment_ATS","PeopleAnalytics_Fact"],
    planted: "Hiring adverse impact (~0.60 ratio with algorithm); flight-risk FPR ~33% Under-30 vs ~12% Over-30",
    signature: true,
    clos: ["CLO3","CLO4","CLO5"],
    theories: [
      "NIST AI RMF -- Govern to Map to Measure to Manage",
      "EEOC Four-Fifths Rule -- adverse impact threshold (>=0.80 selection ratio)",
      "Tambe, Cappelli & Yakubovich (2019) -- Artificial intelligence in human resource management",
      "Kellogg, Valentine & Christin (2020) -- Algorithms at Work",
      "Leicht-Deobald et al. (2019) -- Challenges of employee-generated data",
      "ISO 23894 -- HITL as continuous lifecycle requirement",
      "DPDP Act 2023 -- consent for algorithmic use of employee data",
    ],
    anchorsActive: ["GL-1004","GL-1001"],
    assessments: ["Quiz 4"],
    options: [
      {
        code: "4A", name: "Bias Audit + Retraining",
        tagline: "Full algorithmic audit; retrain on debiased data; document for DPDP",
        cost: { budget: 80, hours: 18, cc: 5 },
        theory: "NIST AI RMF -- Measure function (the audit) combined with the Manage function (this option). Tambe et al. (2019): the path forward requires auditing training data and model architecture, not just outputs. Leicht-Deobald: algorithmic decisions must be contestable and explainable under DPDP. Addresses root cause rather than symptoms -- the only option that prevents recurrence rather than managing consequences.",
        clos: ["CLO3","CLO4","CLO5"],
        lectureLink: "W9 L2 -- bias sources in models · W9 L3 -- accountability frameworks · W7 -- analytics Manage function",
        pedagogy: "Strongest on Equity & Compliance axis. The anchor question: if GL-1004 Shreya Iyer's false positive is not corrected at the data level, how many future Shreyas will face the same harm?",
        grade: "strong",
      },
      {
        code: "4B", name: "Human-in-the-Loop Override",
        tagline: "Mandatory HR review for all high-stakes algorithmic outputs",
        cost: { budget: 60, hours: 12, cc: 8 },
        theory: "ISO 23894: HITL design is a continuous lifecycle process, not a one-time review event. Kellogg et al. (2020): algorithms create a contested terrain of control -- HITL restores human agency without dismantling the system. Leicht-Deobald: the right to contest algorithmic decisions as a matter of personal integrity. Critical limitation: does not fix the model. The underlying FPR disparity persists and accrues as Debt Ledger debt unless 4A follows.",
        clos: ["CLO3","CLO5"],
        lectureLink: "W9 L3 -- HITL design · W8 L3 -- KPI frameworks (who reviews, at what cadence)",
        pedagogy: "Highest Change Capital option: earns trust while preserving speed. But teams must acknowledge the residual debt explicitly to avoid a BCI Risk Transparency penalty.",
        grade: "strong",
      },
      {
        code: "4C", name: "Explainability Dashboard",
        tagline: "Manager-facing layer showing why the model flagged each employee",
        cost: { budget: 70, hours: 15, cc: 6 },
        theory: "Explainable AI (XAI) and fairness-by-design. NIST AI RMF: transparency as a governance dimension. Tambe et al.: explainability increases trust but does not correct the underlying model. Manuti & de Palma (2023): transparency tools can perform accountability without delivering it -- a form of fairwashing. Leicht-Deobald: explanation alone does not address the challenge to personal integrity when the model remains biased at source.",
        clos: ["CLO3","CLO5"],
        lectureLink: "W8 L1 -- dashboard design · W9 L2 -- competing fairness definitions · W9 L1 -- algorithmic decisions",
        pedagogy: "Teaches the critical distinction between transparency and accountability. An excellent paired debrief question: Does seeing why Shreya was flagged wrongly protect her -- or does it just make the harm more legible?",
        grade: "caution",
      },
      {
        code: "4D", name: "Suspend Model + Manual Process",
        tagline: "Suspend algorithmic decision-making entirely; revert to manual HR",
        cost: { budget: 30, hours: 8, cc: -5 },
        theory: "Precautionary principle in AI governance: when harm is demonstrated and remedy is uncertain, suspension is the appropriate response. Kellogg et al. (2020): pulling back algorithmic control can restore trust, but at high operational cost. NIST AI RMF: sometimes the Manage function means do not deploy. Critical trade-off: safest for employees, highest operational cost, lowest Financial Discipline score -- and the only option that is honest about the severity of a 33% FPR among Under-30 employees.",
        clos: ["CLO3","CLO5"],
        lectureLink: "W9 L2 -- precautionary principle · W9 L3 -- accountability vs operational cost",
        pedagogy: "The intellectually most honest option when the model is seriously biased. Teaches that suspend is a legitimate governance decision, not a failure. The CFO challenge will be fierce -- which is the point.",
        grade: "caution",
      },
    ],
  },
  {
    id: "R5", code: "R5",
    title: "The Story",
    subtitle: "People Analytics, Data Storytelling & the CHRO Dashboard",
    unit: "Unit III-IV", weeks: "Weeks 9-10",
    color: "#C07A10", colorLight: "#FEF5E4", colorDark: "#7A4C06", colorMid: "#E0A83C",
    dataset: ["PeopleAnalytics_Fact","Gig_Workforce"],
    planted: "Real attrition drivers: low engagement (-0.7 gap), manager effectiveness (-0.49); age is a spurious proxy",
    shock: {
      title: "Shock 2 -- Viral Gig-Worker Grievance",
      text: "GL-1002 Arjun Joshi's post shared 4,200 times in 18 hours. Allegations are accurate: Bronze earnings ~Rs 7,361 vs Gold ~Rs 19,014 (61% gap); SS2020 enrollment gap 34.6 percentage points. Verify Gig_Workforce before writing.",
      color: "#C07A10",
    },
    clos: ["CLO3","CLO4","CLO5"],
    theories: [
      "Knaflic -- Storytelling with Data (headline to 3 metrics to counter-metric to decision ask)",
      "Levy (2018) -- People Analytics (promise, practice, and surveillance risk)",
      "Spurious correlation & proxy problem (age is not attrition cause)",
      "Kellogg, Valentine & Christin (2020) -- Algorithmic management in gig work",
      "Code on Social Security 2020 -- SS2020 gig worker benefits eligibility",
      "Crisis communications theory -- first response within 24 hours",
    ],
    anchorsActive: ["GL-1002","GL-1003"],
    assessments: ["Quiz 5"],
    options: [
      {
        code: "5A", name: "Gig-Worker Digital Integration",
        tagline: "Extend HRMS to formally onboard gig workers -- digital contracts, grievance portal, benefits visibility",
        cost: { budget: 80, hours: 16, cc: 5 },
        theory: "Code on Social Security 2020: extending ESIC/EPF to platform workers who meet the hours/earnings threshold -- non-enrollment of eligible Bronze partners is a legal compliance failure. Kellogg et al. (2020): algorithmic management creates informational asymmetry that must be corrected by system design, not communication campaigns. Directly addresses GL-1002's root cause. Best option for teams who want Equity & Compliance axis strength leading into R6.",
        clos: ["CLO3","CLO4","CLO5"],
        lectureLink: "W9 L3 -- algorithmic accountability · W10 L1 -- gig platform economy · W10 L3 -- R6 strategy brief",
        pedagogy: "Root-cause remediation. The data in Gig_Workforce confirms the allegations -- teams who verified before writing the shock response have already built the case for choosing 5A.",
        grade: "strong",
      },
      {
        code: "5B", name: "Communications & Transparency Sprint",
        tagline: "Town halls, explainer videos, manager briefings -- rapid crisis communication",
        cost: { budget: 40, hours: 8, cc: 8 },
        theory: "Crisis communications: first response must be on-channel within 24 hours. Levy (2018): data storytelling as trust-building when the narrative is honest. Critical limitation: does not fix underlying policy gaps -- consistent with Angrave et al.'s critique that HR analytics PR does not equal HR analytics practice. The highest Change Capital gain of any R5 option but the lowest structural impact. A team that chooses 5B and 6C together can still close the loop.",
        clos: ["CLO4","CLO5"],
        lectureLink: "W8 L2 -- data storytelling · W11 L2 -- HR as change agent · W10 L1 -- gig regulation",
        pedagogy: "Teaches that communication is necessary but insufficient. Debrief: Does telling Arjun that you've heard him solve the Bronze earnings gap?",
        grade: "caution",
      },
      {
        code: "5C", name: "Policy Review + Grievance SLA",
        tagline: "Formal policy review, 48-hour grievance SLA, published outcomes",
        cost: { budget: 60, hours: 12, cc: 6 },
        theory: "Procedural justice: fair processes matter as much as fair outcomes. Kellogg et al. (2020): algorithm contestability requires a grievance pathway with a published SLA -- the 48-hour commitment is the mechanism. Levy (2018): data-driven HR must be accountable to employees, not just the Board. Intermediate between 5A (root cause) and 5B (communications only). Links to NIST AI RMF's Manage function for algorithmic harm.",
        clos: ["CLO3","CLO5"],
        lectureLink: "W9 L3 -- accountability · W10 L1 -- gig regulation · W11 L2 -- HR change agency",
        pedagogy: "Teaches procedural justice as an independent axis of fairness. Strongest paired with 5A in the D2 remediation table.",
        grade: "strong",
      },
      {
        code: "5D", name: "Third-Party Mediation",
        tagline: "Independent mediator investigates and publishes findings",
        cost: { budget: 50, hours: 10, cc: 3 },
        theory: "Alternative dispute resolution (ADR): neutral third party restores trust when internal credibility is compromised. Highest external credibility because the Board cannot be seen to mark its own homework. Highest reputational risk: published findings will confirm the GL-1002 allegations publicly (Bronze earnings ~Rs 7,361, 34.6pp SS2020 enrollment gap are both verified in the data). Links to W9 L2 competing fairness definitions: who has the authority to define fairness?",
        clos: ["CLO3","CLO5"],
        lectureLink: "W10 L1 -- gig regulation and governance · W9 L3 -- who is accountable for algorithmic outcomes",
        pedagogy: "The most philosophically interesting R5 option. Forces the team to own the risk of external scrutiny -- which is exactly what institutional accountability requires.",
        grade: "caution",
      },
    ],
  },
  {
    id: "R6", code: "R6",
    title: "The Future",
    subtitle: "Future of Work, Gig Regulation, Workforce Automation & Strategic HR",
    unit: "Unit IV", weeks: "Weeks 11-12",
    color: "#2277CC", colorLight: "#E8F2FF", colorDark: "#10427A", colorMid: "#5599E8",
    dataset: ["Gig_Workforce","Workforce_Planning"],
    planted: "Automation risk scores (>0.70 Critical); gig earnings inequity; SS2020 enrollment gap",
    deliverable: "D2 -- Future-of-Work Board Memo (due close of R6)",
    clos: ["CLO1","CLO4","CLO5"],
    theories: [
      "Code on Social Security 2020 -- gig worker ESIC/EPF provisions and compliance",
      "Scully-Russ (2019) -- HR as digital transformation change agent",
      "WEF / Deloitte Insights -- Future of Work automation risk taxonomy",
      "Kavanagh -- Strategic HR Futures: anticipator not administrator",
      "Susskind (2020) -- A World Without Work (automation and human displacement)",
      "Gratton (2021) -- How to Do Hybrid Right (equity traps in distributed work)",
      "NITI Aayog (2022) -- India's gig and platform economy",
      "6B Framework: Build / Buy / Borrow / Bridge / Bot / Exit",
    ],
    anchorsActive: ["GL-1002","GL-1001"],
    assessments: ["Quiz 5","D2"],
    options: [
      {
        code: "6A", name: "Scale & Sustain",
        tagline: "Scale proven digital HR stack -- expand coverage, deepen analytics, institutionalise governance",
        cost: { budget: 100, hours: 15, cc: 5 },
        theory: "Kavanagh Stage 4-5: from optimised to strategic. Westerman et al. (2014): scaling digital capability is a leadership discipline, not a technology task -- requires deliberate change management. Scully-Russ (2019): HR as anticipator means institutionalising what works before pivoting to the next initiative. Most coherent with a foundations first R1 decision sequence. The 6B workforce classification must still be included or the D2 Board Memo is incomplete.",
        clos: ["CLO1","CLO4","CLO5"],
        lectureLink: "W11 L1 -- digital-HR strategy for resilience · W12 -- presentations and synthesis",
        pedagogy: "The consolidation thesis. Strongest for teams who chose 1A to 2A to 3C and built steadily. The BCI trajectory should show consistent improvement -- the Board memo is the proof.",
        grade: "strong",
      },
      {
        code: "6B", name: "Future-of-Work Pivot",
        tagline: "Predictive workforce planning, generative AI for L&D, skills-based talent marketplace",
        cost: { budget: 120, hours: 20, cc: 0 },
        theory: "WEF / Deloitte Insights: skills-based organisations as the future of talent architecture -- jobs replaced by tasks, tasks by skills. Susskind (2020): automation creates displacement that HR must anticipate rather than react to. Davenport et al. (2010): prescriptive analytics is the top of the analytics ladder -- the ladder students have been climbing since R1. High potential but requires the data quality infrastructure built in R1-R5 to deliver. Zero Change Capital delta reflects the uncertainty: ambition without a track record generates neither trust nor fear.",
        clos: ["CLO1","CLO3","CLO4"],
        lectureLink: "W10 L3 -- R6 strategy brief · W11 L1 -- resilience/agility · W11 L2 -- HR as change agent",
        pedagogy: "Coherence test: does the team's BCI trajectory over five rounds justify this level of Board ambition? Future-of-Work rhetoric without a governance and equity foundation scores poorly on Strategic Coherence.",
        grade: "caution",
      },
      {
        code: "6C", name: "Equity Consolidation",
        tagline: "Close Tier-3 gap, formalise SS2020 enrollment, publish DPDP compliance report",
        cost: { budget: 80, hours: 12, cc: 10 },
        theory: "Digital inclusion: closes the access-and-literacy gap that R1 diagnosed but R3 only partially narrowed. Code on Social Security 2020: non-enrollment of eligible Bronze partners is a compliance failure requiring a named remediation timeline. ESG HR disclosure: publishing the DPDP compliance report as a governance signal to the Board. Highest Change Capital gain of any R6 option. Corresponds to the Digital Equity Leader culture profile in the final debrief.",
        clos: ["CLO4","CLO5"],
        lectureLink: "W10 L1 -- gig regulation · W11 L1 -- strategy · W12 -- D2 coherence test: does R6 close the loops from R1?",
        pedagogy: "The thesis that returns to its starting point: R1 diagnosed the divide, R6C resolves it. The strongest D2 board memos will draw a direct line from GL-1001's literacy score to the SS2020 enrollment gap closure.",
        grade: "strong",
      },
      {
        code: "6D", name: "Governance & Audit Framework",
        tagline: "Permanent HR tech governance board, algorithmic audit cadence, living policy framework",
        cost: { budget: 70, hours: 14, cc: 8 },
        theory: "AI governance: institutionalising the lessons from R3 (DPDP breach), R4 (biased model), and R5 (gig grievance) into a permanent governance architecture. NIST AI RMF: the Govern function is iterative and continuous, not a one-time fix -- it requires a board, a cadence, and a living policy. ISO 23894: HITL and audit cadence as ongoing obligations. Kavanagh's strategic anticipator: governance is what separates a reacting HR function from a leading one.",
        clos: ["CLO3","CLO4","CLO5"],
        lectureLink: "W9 L3 -- accountability · W11 L1 -- operating model for resilience · W12 -- five-axis synthesis",
        pedagogy: "The intellectually most honest R6 option: what structural change prevents the R3, R4, and R5 events from recurring? Strongest for teams whose BCI shows they learned from each crisis rather than just surviving them.",
        grade: "strong",
      },
    ],
  },
];
